spring:
  config:
    import:
      - optional:file:.env.dev

  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


  task:
    execution:
      pool:
        core-size: 5
        max-size: 20

  jackson:
    time-zone: Asia/Seoul

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      expirationForPut: 1
      expirationForGet: 24
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      stack:
        auto: false
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}



#  mvc:
#    favicon:
#      enabled: false

# Frontend URL for CORS configuration
front:
  url: ${FRONT_URL:http://localhost:3000}

# JWT Configuration

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    
# Apify API 설정 : 인스타그램 설정
apify:
  api:
    key1: ${APIFY_API_KEY_1}
    key2: ${APIFY_API_KEY_2}
    key3: ${APIFY_API_KEY_3}
    key4: ${APIFY_API_KEY_4}
    key5: ${APIFY_API_KEY_5}
    key6: ${APIFY_API_KEY_6}
    key7: ${APIFY_API_KEY_7}
    key8: ${APIFY_API_KEY_8}
    key9: ${APIFY_API_KEY_9}
    key10: ${APIFY_API_KEY_10}
    key11: ${APIFY_API_KEY_11}
    key12: ${APIFY_API_KEY_12}
  base-url: https://api.apify.com/v2

api:
  key: ${API_KEY}  # Leaper와 같은 키


youtube:
  api:
    key1: ${YOUTUBE_API_V3_KEY_1}
    key2: ${YOUTUBE_API_V3_KEY_2}
    key3: ${YOUTUBE_API_V3_KEY_3}
    base-url: https://www.googleapis.com/youtube/v3

spark:
  server:
    protocol: ${SPARK_SERVER_PROTOCOL}
    host: ${SPARK_SERVER_HOST}  # 또는 실제 Spark 서버 주소
    port: ${SPARK_SERVER_PORT}      # Spark 서버 포트
  api:
    key: ${SPARK_API_KEY}

server:
  port: 8080