spring:
  datasource:
    #    url: jdbc:mysql://tmi.c3kcossmihcm.ap-northeast-2.rds.amazonaws.com:3306/tmi?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    #    username: ssafy
    #    password: publicstaticvoidmain
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leaper?serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계에서는 update, 운영에서는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



#cloud:
#  aws:
#    s3:
#      bucket: ${S3_BUCKET_NAME}
#      expirationForPut: 1
#      expirationForGet: 24
#    credentials:
#      accessKey: ${S3_ACCESS_KEY}
#      secretKey: ${S3_SECRET_KEY}
#    region:
#      static: ap-northeast-2
#      stack:
#        auto: false

cloud:
  aws:
    s3:
      bucket: ASDFASDFASDFASDFSADFSFDSFDSAFD
      expirationForPut: 1
      expirationForGet: 24
    credentials:
      accessKey: ASDFASDFASDFASDFSADFSFDSFDSAFD
      secretKey: ASDFASDFASDFASDFSADFSFDSFDSAFD
    region:
      static: ap-northeast-2
      stack:
        auto: false